name : Auto Deploy Hospital Management System

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 13.51.201.122 >> ~/.ssh/known_hosts
      - name: Frontend deploy
        run : |
            cd frontend
            npm install
            npm run build
      - name: Upload Frontend
        run : |
             rsync -av frontend/dist/ \
              ubuntu@${{ secrets.EC2_SSH_PRIVATE_KEY }}:/var/www/frontend/

      - name: Backend deploy
        run: |
          ssh ubuntu@${{ secrets.EC2_SSH_PRIVATE_KEY }} << 'EOF'
            cd /var/www/backend
            git pull origin main
            npm install --production
            pm2 reload hospital-management-system
          EOF